(function(){var s=document.createElement('style');s.id='gmm-css';s.textContent='#gmm{position:fixed;inset:0;z-index:99999;visibility:hidden;pointer-events:none;display:flex;flex-direction:column;overflow:hidden;--k:1;transition:visibility 0s .55s;color:#000;font-family:"Neuehaasdisplay Roman",Arial,sans-serif}#gmm.on{visibility:visible;pointer-events:auto;transition:none}#gmm a{text-decoration:none;color:#000}.gmm-bg{position:fixed;inset:0;background:#fff;transform:scaleY(0);transform-origin:top;transition:transform .55s cubic-bezier(.7,0,.2,1)}#gmm.on .gmm-bg{transform:none}#gmm>:not(.gmm-bg){position:relative}.gmm-bar{flex:none;opacity:0;transition:opacity .25s}#gmm.on .gmm-bar{opacity:1}.gmm-bar>*{position:absolute}.gmm-x{background:none;border:0;padding:0;cursor:pointer}.gmm-x i{position:absolute;left:50%;top:50%;width:26px;height:1.5px;margin-left:-13px;background:#000;transform:rotate(45deg)}.gmm-x i+i{transform:rotate(-45deg)}.gmm-w{border-top:.5px solid #000}.gmm-b{display:block;overflow:hidden;color:#000;border-bottom:.5px solid #000;padding:calc(6px*var(--k)) 20px calc(4px*var(--k));font:400 calc(clamp(40px,13.5vw,64px)*var(--k))/.95 "Neuehaasdisplay Mediu","Neuehaasdisplay Roman",Arial,sans-serif;letter-spacing:-.05em}.gmm-b.n{border-bottom:0}.gmm-b span{display:block;transform:translateY(105%);transition:transform .6s cubic-bezier(.7,0,.2,1)}#gmm.on .gmm-b span{transform:none}#gmm .c,#gmm .gmm-s a.c,#gmm .gmm-l a.c{color:#ff4a1c}.gmm-s{border-bottom:.5px solid #000;padding:calc(4px*var(--k)) 20px calc(14px*var(--k)) 50px}#gmm .gmm-s a{display:block;font-size:calc(15px*var(--k));line-height:1.8;color:#3e404e}.gmm-f{margin-top:auto;padding:calc(28px*var(--k)) 20px;display:flex;justify-content:space-between;align-items:center}.gmm-cta{background:#000;color:#fff!important;border-radius:999px;padding:14px 24px;font-size:15px}#gmm .gmm-l a{margin-left:16px;font-size:12px;letter-spacing:.14em;text-transform:uppercase;color:#7c809b}.gmm-s,.gmm-f{opacity:0;transform:translateY(14px);transition:opacity .4s,transform .5s cubic-bezier(.7,0,.2,1)}#gmm.on .gmm-s,#gmm.on .gmm-f{opacity:1;transform:none;transition-delay:.3s}@media(prefers-reduced-motion:reduce){#gmm *{transition:none!important}}';document.head.appendChild(s)})();
(function(){var mq=matchMedia('(max-width:991px)'),ov,last;
function q(s,r){return(r||document).querySelector(s)}
function cur(h){var p=location.pathname.replace(/\/$/,'');return h&&h.length>3&&(p==h||p.indexOf(h+'/')==0)}
function L(a,c,t){var h=a.getAttribute('href');return'<a href="'+h+'" class="'+(c||'')+(cur(h)?' c':'')+'">'+(t||a.textContent.trim())+'</a>'}
function build(){var m=q('.w-nav-menu');if(!m)return;var s='',seen={},b='',pr,i=1,top=q('.w-dropdown-toggle a',m);
[].slice.call(m.querySelectorAll('.w-dropdown-link')).reverse().forEach(function(a){var h=a.getAttribute('href');if(!seen[h]){seen[h]=1;s=L(a)+s}});
m.querySelectorAll('a.w-nav-link').forEach(function(a){if(a==top)return;if(/pakiet-mala-firma/.test(a.href))pr=a;else b+=L(a,'gmm-b','<span style="transition-delay:'+(i++*.05)+'s">'+a.textContent.trim()+'</span>')});
if(pr)s+=L(pr);var cta=q('.nav-cta',m),ls='';m.querySelectorAll('.n_jezyk').forEach(function(a){ls+='<a href="'+a.getAttribute('href')+'"'+(a.classList.contains('w--current')?' class="c"':'')+'>'+a.getAttribute('hreflang')+'</a>'});
var br=q('.w-nav-brand');ov=document.createElement('div');ov.id='gmm';ov.setAttribute('role','dialog');ov.setAttribute('aria-modal','true');
ov.innerHTML='<div class="gmm-bg"></div><div class="gmm-bar"><a class="gmm-lg" href="'+br.getAttribute('href')+'">'+br.innerHTML+'</a><button class="gmm-x" aria-label="close"><i></i><i></i></button></div><nav class="gmm-w">'+(top?L(top,'gmm-b n','<span>'+top.textContent.trim()+'</span>'):'')+'<div class="gmm-s">'+s+'</div>'+b+'</nav><div class="gmm-f">'+(cta?L(cta,'gmm-cta','→ '+cta.textContent.trim()):'')+'<div class="gmm-l">'+ls+'</div></div>';
document.body.appendChild(ov);q('.gmm-x',ov).onclick=close}
function pos(el,r){el.style.cssText='top:'+Math.max(r.top,8)+'px;left:'+r.left+'px;width:'+r.width+'px;height:'+r.height+'px'}
function open(btn){if(!ov)build();if(!ov)return;last=btn;var r=btn.getBoundingClientRect(),br=q('.w-nav-brand').getBoundingClientRect();pos(q('.gmm-x',ov),r);pos(q('.gmm-lg',ov),br);q('.gmm-bar',ov).style.height=Math.max(r.bottom,br.bottom,60)+12+'px';fit();ov.classList.add('on');document.documentElement.style.overflow='hidden';q('.gmm-x',ov).focus({preventScroll:true})}
function fit(){var H=ov.clientHeight,lo=.4,hi=1,m,ok=function(k){ov.style.setProperty('--k',k);return ov.scrollHeight<=H+1};if(ok(1))return;for(var n=0;n<8;n++){m=(lo+hi)/2;ok(m)?lo=m:hi=m}ov.style.setProperty('--k',lo)}
function close(){if(!ov)return;ov.classList.remove('on');document.documentElement.style.overflow='';last&&last.focus&&last.focus({preventScroll:true})}
function hit(e){var b=e.target.closest&&e.target.closest('.w-nav-button');if(!b||!mq.matches||e.type=='keydown'&&!/^(Enter| )$/.test(e.key))return;e.stopImmediatePropagation();if(/start|down$/.test(e.type)&&e.type!='keydown')return;e.preventDefault();if(e.type!='mouseup')open(b)}
['click','touchstart','touchend','mousedown','mouseup','keydown'].forEach(function(t){window.addEventListener(t,hit,true)});
addEventListener('keydown',function(e){if(e.key=='Escape')close()});mq.addEventListener('change',function(){if(!mq.matches)close()});addEventListener('resize',function(){ov&&ov.classList.contains('on')&&fit()})})();
